# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
#   "iPhone 7",
#   "iPhone 7 Plus",
#   "iPhone SE",
#  "iPad Air 2",
   "iPad Pro (12.9-inch)",
   "iPhone 4s",
 ])

languages([
  "en-US",
  "es-ES",
])

# The name of the scheme which contains the UI Tests
scheme "WorkRosterApp"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
launch_arguments(["-defaultWorkScheme M,M,M,M,X,X,A,A,A,A,X,X"])

# For more information about all available options run
# fastlane snapshot --help

#clear_previous_screenshots true